services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
    env_file:
      - path: .env
        required: false
    environment:
      HOST: 0.0.0.0
      PORT: '3000'
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
